{{- if .Values.ingress.enabled -}}
{{- $fullName := include "nexus.fullname" . -}}
{{- $labelsExtra := include "nexus.labelsExtra" . -}}
---
{{- if (semverCompare "<=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: networking.k8s.io/v1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels: {{ $labelsExtra | nindent 4 }}
  annotations: {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  {{- if and (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) .Values.ingress.ingressClass }}
  ingressClassName: {{ .Values.ingress.ingressClass }}
  {{- end }}
  {{- if .Values.ingress.tls.secretName }}
  tls:
    - hosts: {{- toYaml .Values.ingress.hosts | nindent 8 }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: {{ $.Values.ingress.path }}
            {{- if (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: Prefix
            {{- end }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: 8081
    {{- end }}
...
{{- range $connector := .Values.ingress.connectors }}
---
{{- if (semverCompare "<=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: networking.k8s.io/v1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName | trunc 49 }}-docker-{{ $connector.port }}
  labels: {{ $labelsExtra | nindent 4 }}
  annotations: {{- toYaml $.Values.ingress.annotations | nindent 4 }}
spec:
  {{- if and (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) (or $connector.ingressClass $.Values.ingress.ingressClass) }}
  ingressClassName: {{ $connector.ingressClass | default $.Values.ingress.ingressClass }}
  {{- end }}
  {{- if $connector.tls.secretName }}
  tls:
    - hosts: {{ toYaml $connector.hosts | nindent 8 }}
      secretName: {{ $connector.tls.secretName }}
  {{- end }}
  rules:
    {{- range $host := $connector.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            {{- if (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: Prefix
            {{- end }}
            backend:
              serviceName: {{ $fullName | trunc 49 }}-connector-{{ $connector.port }}
              servicePort: {{ $connector.port }}
    {{- end }}
...
{{- end -}}
{{- end }}
