{{- if .Values.service.enabled -}}
{{- $labelsExtra := include "nexus.labelsExtra" . -}}
{{- $selectorLabelsExtra := include "nexus.selectorLabelsExtra" . -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus.fullname" . }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  labels: {{- $labelsExtra | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.nexus.nexusPort }}
      protocol: TCP
      name: http-nexus-ui
  selector: {{- $selectorLabelsExtra | nindent 4 }}
...
{{- range $connector := .Values.ingress.connectors }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus.fullname" $ | trunc 49 }}-connector-{{ $connector.port }}
{{- if $.Values.service.annotations }}
  annotations:
{{ toYaml $.Values.service.annotations | indent 4 }}
{{- end }}
  labels: {{- $labelsExtra | nindent 4 }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $connector.port }}
      protocol: TCP
      name: http-{{ $connector.port }}
  selector: {{- $selectorLabelsExtra | nindent 4 }}
...
{{- end }}
{{- end }}
